// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTZxuser = "t_zxuser"

// TZxuser 咨询用户
type TZxuser struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	SourceID    string    `gorm:"column:source_id;comment:注册ID" json:"source_id"`               // 注册ID
	SourceType  bool      `gorm:"column:source_type;comment:注册类别" json:"source_type"`           // 注册类别
	Recommender string    `gorm:"column:recommender;comment:推荐人" json:"recommender"`            // 推荐人
	NickName    string    `gorm:"column:nick_name;comment:昵称" json:"nick_name"`                 // 昵称
	Avatar      string    `gorm:"column:avatar;comment:头像" json:"avatar"`                       // 头像
	ZjID        int64     `gorm:"column:zj_id;comment:专家ID" json:"zj_id"`                       // 专家ID
	Status      int32     `gorm:"column:status;comment:状态" json:"status"`                       // 状态
	CreateTime  time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`           // 更新时间
}

// TableName TZxuser's table name
func (*TZxuser) TableName() string {
	return TableNameTZxuser
}
